// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_oauth_callback from "./routes/admin/oauth/callback.ts";
import * as $admin_oauth_signin from "./routes/admin/oauth/signin.ts";
import * as $admin_oauth_signout from "./routes/admin/oauth/signout.ts";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $api_onboarding_complete from "./routes/api/onboarding/complete.ts";
import * as $api_onboarding_onboard from "./routes/api/onboarding/onboard.ts";
import * as $api_query from "./routes/api/query.ts";
import * as $api_track from "./routes/api/track.ts";
import * as $app_middleware from "./routes/app/_middleware.ts";
import * as $app_dashboard from "./routes/app/dashboard.tsx";
import * as $app_index from "./routes/app/index.tsx";
import * as $app_loading from "./routes/app/loading.tsx";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $index from "./routes/index.tsx";
import * as $onboarding_middleware from "./routes/onboarding/_middleware.ts";
import * as $onboarding_plans from "./routes/onboarding/plans.tsx";
import * as $DashboardData from "./islands/DashboardData.tsx";
import * as $DashboardTabs from "./islands/DashboardTabs.tsx";
import * as $DashboardWithPlots from "./islands/DashboardWithPlots.tsx";
import * as $DataCatalog from "./islands/DataCatalog.tsx";
import * as $NaturalLanguageQuery from "./islands/NaturalLanguageQuery.tsx";
import * as $ObservablePlot from "./islands/ObservablePlot.tsx";
import * as $PieLoading from "./islands/PieLoading.tsx";
import * as $PivotTable from "./islands/PivotTable.tsx";
import * as $PlanSelection from "./islands/PlanSelection.tsx";
import * as $ScrollToTop from "./islands/ScrollToTop.tsx";
import * as $ScrollingMenu from "./islands/ScrollingMenu.tsx";
import * as $SimplePivot from "./islands/SimplePivot.tsx";
import * as $onboarding_PlanSelection from "./islands/onboarding/PlanSelection.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/oauth/callback.ts": $admin_oauth_callback,
    "./routes/admin/oauth/signin.ts": $admin_oauth_signin,
    "./routes/admin/oauth/signout.ts": $admin_oauth_signout,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/api/onboarding/complete.ts": $api_onboarding_complete,
    "./routes/api/onboarding/onboard.ts": $api_onboarding_onboard,
    "./routes/api/query.ts": $api_query,
    "./routes/api/track.ts": $api_track,
    "./routes/app/_middleware.ts": $app_middleware,
    "./routes/app/dashboard.tsx": $app_dashboard,
    "./routes/app/index.tsx": $app_index,
    "./routes/app/loading.tsx": $app_loading,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/index.tsx": $index,
    "./routes/onboarding/_middleware.ts": $onboarding_middleware,
    "./routes/onboarding/plans.tsx": $onboarding_plans,
  },
  islands: {
    "./islands/DashboardData.tsx": $DashboardData,
    "./islands/DashboardTabs.tsx": $DashboardTabs,
    "./islands/DashboardWithPlots.tsx": $DashboardWithPlots,
    "./islands/DataCatalog.tsx": $DataCatalog,
    "./islands/NaturalLanguageQuery.tsx": $NaturalLanguageQuery,
    "./islands/ObservablePlot.tsx": $ObservablePlot,
    "./islands/PieLoading.tsx": $PieLoading,
    "./islands/PivotTable.tsx": $PivotTable,
    "./islands/PlanSelection.tsx": $PlanSelection,
    "./islands/ScrollToTop.tsx": $ScrollToTop,
    "./islands/ScrollingMenu.tsx": $ScrollingMenu,
    "./islands/SimplePivot.tsx": $SimplePivot,
    "./islands/onboarding/PlanSelection.tsx": $onboarding_PlanSelection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
