// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_contacts from "./routes/admin/contacts.tsx";
import * as $admin_contacts_id_ from "./routes/admin/contacts/[id].ts";
import * as $admin_oauth_callback from "./routes/admin/oauth/callback.ts";
import * as $admin_oauth_signin from "./routes/admin/oauth/signin.ts";
import * as $admin_oauth_signout from "./routes/admin/oauth/signout.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_contact_id_ from "./routes/api/contact/[id].tsx";
import * as $api_visitor from "./routes/api/visitor.ts";
import * as $index from "./routes/index.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $ScrollToTop from "./islands/ScrollToTop.tsx";
import * as $ScrollingMenu from "./islands/ScrollingMenu.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/contacts.tsx": $admin_contacts,
    "./routes/admin/contacts/[id].ts": $admin_contacts_id_,
    "./routes/admin/oauth/callback.ts": $admin_oauth_callback,
    "./routes/admin/oauth/signin.ts": $admin_oauth_signin,
    "./routes/admin/oauth/signout.ts": $admin_oauth_signout,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/contact/[id].tsx": $api_contact_id_,
    "./routes/api/visitor.ts": $api_visitor,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/ScrollToTop.tsx": $ScrollToTop,
    "./islands/ScrollingMenu.tsx": $ScrollingMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
